name: Michael Thiesen
url: http://www.micthiesen.ca
dateformat: "%-d %B, %Y"

paginate: 5
paginate_path: /page/:num/

exclude: [
  CNAME,
  README.md,
  bower.json,
  Gemfile,
  Gemfile.lock,
  gruntfile.js,
  package.json,
  style.less,
  bower_components,
  node_modules
]

excerpt_separator: <!--more-->
highlighter: pygments

gems:
  - jekyll-sitemap
